### PR TITLE
Add ESLint

### PR DESCRIPTION
**Pull request by tara-matthew**
- This PR adds [ESLint](https://eslint.org/docs/latest/use/getting-started)
- If there are any rules you want changed let me know
- I've also added a script to run the linter
- Once you're happy I can open another PR which runs the linter

### CODE REVIEW

**Comment by PradyumnaKrishna** [comment]
If possible, can you please also add an option to format the files?

**Comment by tara-matthew** [comment]
Thank you for taking a look! 🥳  
The `--fix` option in the `lint` script will reformat the files for you, if that's what you mean?

**Comment by PradyumnaKrishna** [comment]
Lets make it two commands, one that formats the code and one that lints the code only.

**Comment by tara-matthew** [comment]
Sure thing, good idea! I'm away from my computer this evening, but will get this updated for you either later today or tomorrow 👌

**Comment by tara-matthew** [comment]
@PradyumnaKrishna Updated 👌

**Review by PradyumnaKrishna — APPROVED** [review]
Thank you

**Pull request merged**
